version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: regulatoryos-pg
    environment:
      POSTGRES_DB: regulatoryos
      POSTGRES_USER: regulatoryos
      POSTGRES_PASSWORD: regulatoryos_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U regulatoryos"]
      interval: 3s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
